# Generated by Django 5.2.6 on 2025-09-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
